/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LabRepo;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author imado
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdNuevoHijo = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfnhNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spnhEdad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        rbnhM = new javax.swing.JRadioButton();
        rbnhF = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tfnhLugarNacimiento = new javax.swing.JTextField();
        tfnhLugarResidencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbnhSi = new javax.swing.JRadioButton();
        rbnhNo = new javax.swing.JRadioButton();
        btnhAñadir = new javax.swing.JButton();
        tfnhPadre = new javax.swing.JTextField();
        bgSexo = new javax.swing.ButtonGroup();
        bgVivo = new javax.swing.ButtonGroup();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtArbol = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 30)); // NOI18N
        jLabel2.setText("Añadir Nuevo Hijo");

        jLabel3.setText("Padre Seleccionado");

        jLabel4.setText("Nombre");

        jLabel5.setText("Edad");

        jLabel6.setText("Sexo");

        bgSexo.add(rbnhM);
        rbnhM.setSelected(true);
        rbnhM.setText("M");

        bgSexo.add(rbnhF);
        rbnhF.setText("F");
        rbnhF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnhFActionPerformed(evt);
            }
        });

        jLabel7.setText("Lugar de Nacimiento");

        jLabel8.setText("Lugar de Residencia");

        jLabel9.setText("¿Está Vivo?");

        bgVivo.add(rbnhSi);
        rbnhSi.setText("Si");

        bgVivo.add(rbnhNo);
        rbnhNo.setText("No");

        btnhAñadir.setText("Añadir Hijo");
        btnhAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhAñadirActionPerformed(evt);
            }
        });

        tfnhPadre.setEditable(false);
        tfnhPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnhPadreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdNuevoHijoLayout = new javax.swing.GroupLayout(jdNuevoHijo.getContentPane());
        jdNuevoHijo.getContentPane().setLayout(jdNuevoHijoLayout);
        jdNuevoHijoLayout.setHorizontalGroup(
            jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdNuevoHijoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdNuevoHijoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(rbnhSi)
                        .addGap(18, 18, 18)
                        .addComponent(rbnhNo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jdNuevoHijoLayout.createSequentialGroup()
                        .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnhNombre)
                            .addComponent(tfnhLugarNacimiento)
                            .addComponent(tfnhLugarResidencia)
                            .addComponent(btnhAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jdNuevoHijoLayout.createSequentialGroup()
                                .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdNuevoHijoLayout.createSequentialGroup()
                                        .addComponent(spnhEdad)
                                        .addGap(18, 18, 18)
                                        .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(jdNuevoHijoLayout.createSequentialGroup()
                                                .addComponent(rbnhM)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbnhF))))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(tfnhPadre))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jdNuevoHijoLayout.setVerticalGroup(
            jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdNuevoHijoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnhPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnhNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbnhM)
                        .addComponent(rbnhF))
                    .addGroup(jdNuevoHijoLayout.createSequentialGroup()
                        .addComponent(spnhEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnhLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnhLugarResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdNuevoHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbnhSi)
                    .addComponent(rbnhNo))
                .addGap(18, 18, 18)
                .addComponent(btnhAñadir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel1.setText("Árbol Genealógico");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        jtArbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jtArbol);

        jButton2.setText("Añadir Nuevo Hijo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar Persona");

        jButton4.setText("Modificar Persona");

        jButton5.setText("Generar Reporte");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("Guardar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cargar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Salir");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tfnhPadre.setText(getTreeItem().toString());
        mostrarDialogo(jdNuevoHijo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnhAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhAñadirActionPerformed
        if (tfnhPadre.getText().equals("Personas")) {
            char gen;
            
            if (rbnhF.isSelected()) {
                gen = 'F';
            }else{
                gen = 'M';
            }
       
            boolean vive;
            
            if (rbnhNo.isSelected()) {
                vive = false;
            }else{
                vive = true;
            }
            Hijo h = new Hijo(null, tfnhNombre.getText(), (int) spnhEdad.getValue(), gen, tfnhLugarNacimiento.getText(), tfnhLugarResidencia.getText(), vive);
            ArrayList<TreeNode> tns = new ArrayList();
            DefaultMutableTreeNode rn = ((DefaultMutableTreeNode) jtArbol.getModel().getRoot());
            DefaultTreeModel tm = new DefaultTreeModel(null);
            
            for (int i = 0; i < rn.getChildCount(); i++) {
                tns.add(rn.getChildAt(i));
            }
            
            rn.removeAllChildren();
            
            for (TreeNode tn : tns) {
                rn.add(new DefaultMutableTreeNode(tn));
            }
            
            rn.add(new DefaultMutableTreeNode(h));
            tm.setRoot(rn);
            
            jtArbol.setModel(tm);
            jdNuevoHijo.dispose();
                        
        }else{
            char gen;
            
            if (rbnhF.isSelected()) {
                gen = 'F';
            }else{
                gen = 'M';
            }
       
            boolean vive;
            
            if (rbnhNo.isSelected()) {
                vive = false;
            }else{
                vive = true;
            }
            
            Persona padre = (Persona) getTreeItem();
            
            Hijo h = new Hijo(padre, tfnhNombre.getText(), (int) spnhEdad.getValue(), gen, tfnhLugarNacimiento.getText(), tfnhLugarResidencia.getText(), vive);
            
            ArrayList<TreeNode> tns = new ArrayList();
            DefaultMutableTreeNode rn = getTreeNode();
            DefaultTreeModel tm = (DefaultTreeModel) jtArbol.getModel();
            
            for (int i = 0; i < rn.getChildCount(); i++) {
                tns.add(rn.getChildAt(i));
            }
            
            rn = new DefaultMutableTreeNode();
            
            for (TreeNode tn : tns) {
                rn.add(new DefaultMutableTreeNode(tn));
            }
            
            rn.add(new DefaultMutableTreeNode(h));
            
        }
        
        JOptionPane.showMessageDialog(jdNuevoHijo, "Hijo añadido exitosamente");
    }//GEN-LAST:event_btnhAñadirActionPerformed

    private void rbnhFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnhFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnhFActionPerformed

    private void tfnhPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnhPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnhPadreActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        try {
            guardarTodo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar archivo");
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        try {
            leerTodo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al leer archivo");
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        JOptionPane.showMessageDialog(this, "SotaTree v0.1\nSoftware de árbol genealógico.\nCopyright 2017 - getNumericValue");
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI w = new GUI();
                w.setLocationRelativeTo(null);
                w.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.ButtonGroup bgVivo;
    private javax.swing.JButton btnhAñadir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jdNuevoHijo;
    private javax.swing.JTree jtArbol;
    private javax.swing.JRadioButton rbnhF;
    private javax.swing.JRadioButton rbnhM;
    private javax.swing.JRadioButton rbnhNo;
    private javax.swing.JRadioButton rbnhSi;
    private javax.swing.JSpinner spnhEdad;
    private javax.swing.JTextField tfnhLugarNacimiento;
    private javax.swing.JTextField tfnhLugarResidencia;
    private javax.swing.JTextField tfnhNombre;
    private javax.swing.JTextField tfnhPadre;
    // End of variables declaration//GEN-END:variables

    void refrescarArbol(){
       DefaultTreeModel tm = (DefaultTreeModel) jtArbol.getModel();
       DefaultMutableTreeNode root = (DefaultMutableTreeNode) tm.getRoot();
       
        for (int i = 0; i < root.getChildCount(); i++) {
           DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) root.getChildAt(i);
            if (nodo.getChildCount() >  0 && (nodo.getUserObject() instanceof Padre) == false) {
                DefaultMutableTreeNode nodo2 = new DefaultMutableTreeNode((Padre) nodo.getUserObject());
                
                for (int j = 0; j < nodo.getChildCount(); j++) {
                    nodo2.add(new DefaultMutableTreeNode(nodo.getChildAt(i)));
                }
            }
        }
    }

    private void mostrarDialogo(JDialog jd) {
        jd.pack();
        jd.setLocationRelativeTo(this);
        jd.setModal(true);
        jd.setVisible(true);
    }

    private Object getTreeItem() {
        
        try {
            DefaultTreeModel tm = (DefaultTreeModel) jtArbol.getModel();
            DefaultMutableTreeNode n = (DefaultMutableTreeNode) jtArbol.getLastSelectedPathComponent();
            return n.getUserObject();
        } catch (NullPointerException e) {
            return "Personas";
        }
        
    }

    private void cambPadre(Object p) {
    }

    

    private DefaultMutableTreeNode getTreeNode() {
        try {
            DefaultMutableTreeNode n = (DefaultMutableTreeNode) jtArbol.getLastSelectedPathComponent();
            return n;
        } catch (NullPointerException e) {
            return null;
        }
    }

    private void guardarTodo() throws FileNotFoundException, IOException {
        JFileChooser jfc = new JFileChooser();
        jfc.showSaveDialog(this);
        File f = (jfc.getSelectedFile());
        
        FileOutputStream fos = new FileOutputStream(f);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        
        oos.writeObject(jtArbol.getModel());
        oos.flush();
        
        JOptionPane.showMessageDialog(this, "Datos guardados exitosamente");
    }

    private void leerTodo() throws IOException, ClassNotFoundException {
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        File f = (jfc.getSelectedFile());
        
        FileInputStream fos = new FileInputStream(f);
        ObjectInputStream oos = new ObjectInputStream(fos);
        
        DefaultTreeModel tm = (DefaultTreeModel) oos.readObject();
        jtArbol.setModel(tm);
        
        JOptionPane.showMessageDialog(this, "Datos leidos exitosamente");
    }
}
